# https://github.com/P3TERX/ActionsVM

name: Ubuntu (tmate)

on:
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ^3.9

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Set up protobuf-compiler
      run: |
        sudo apt install -y --no-recommends --no-suggests protobuf-compiler

    - name: Run Start Script
      run: source ubuntu-start.sh

    - name: Start SSH via tmate
      uses: zijianjiao2017/ssh2actions@main
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Run End Script
      run: source ubuntu-end.sh
